name: run tests and deploy

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm run coverage

      - name: Check coverage threshold
        run: |
          COVERAGE=$(npm run coverage | grep -o 'Lines.*: .*%' | grep -o '[0-9.]*')
          if (( $(echo "$COVERAGE < 90" | bc -l) )); then
            echo "Coverage ($COVERAGE%) is below 90%"
            exit 1
          fi
